baseURL = "https://tour.dgraph.io"
languageCode = "en-us"
title = "A Tour of Dgraph"
theme="hugo-tutorials"

[[menu.main]]
  name = "sample"
  url = "/sample/"
  identifier = "sample"
  weight = 1
[[menu.main]]
  name = "intro"
  url = "/intro/"
  identifier = "intro"
  weight = 2
  